"""Add sold field

Revision ID: 4ecbb2bac860
Revises: 12f1de3a07b5
Create Date: 2025-08-03 16:36:02.165812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecbb2bac860'
down_revision: Union[str, Sequence[str], None] = '12f1de3a07b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sold', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sold')
    # ### end Alembic commands ###
