[project]
name = "official-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.116.1",
]

[dependency-groups]
dev = [
    "httpie>=3.2.4",
]
